# Generated by Django 5.0.6 on 2024-07-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customuser_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('member_id', models.CharField(max_length=50)),
                ('left_customer', models.IntegerField(default=0)),
                ('right_customer', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0)),
                ('rebirth', models.BooleanField(default=False)),
                ('income', models.FloatField(default=0)),
                ('count', models.IntegerField()),
                ('si_no', models.AutoField(primary_key=True, serialize=False)),
                ('formatted_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
