# Generated by Django 5.0.6 on 2024-07-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_login_ph_login_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='username',
        ),
    ]
