# Generated by Django 5.0.6 on 2024-07-23 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_user_name_login_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='formatted_date',
        ),
        migrations.RemoveField(
            model_name='home',
            name='income',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='home',
            name='si_no',
        ),
        migrations.AddField(
            model_name='home',
            name='si_number',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='home',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='home',
            name='member_id',
            field=models.CharField(blank=True, max_length=10000, null=True, unique=True),
        ),
    ]
